#код с официального compose.yaml от Redash с гита
x-redash-service: &redash-service
  image: redash/redash:latest # здесь было __TAG__, как я поняла, он заменяется скриптом setup.sh, но на винде я его не запущу, поэтому
                              #использую последнюю версию, а из самого файла взяла основную конфигурацию
  depends_on:
    - redash-postgres
    - redis
  env_file: .env.redash
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"

  scheduler:
    <<: *redash-service
    command: scheduler

  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  redash-postgres:
    image: pgautoupgrade/pgautoupgrade:17-alpine
    env_file: .env.redash
    volumes:
      - redash_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server

  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 1

  weather-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5432:5432"
    volumes:
      - weather_postgres_data:/var/lib/postgresql/data

  data-generator:
    build: ./generator
    depends_on:
      - weather-postgres
    environment:
      DB_HOST: weather-postgres
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass

volumes:
  redash_postgres_data:
  weather_postgres_data:
